version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: test123456
      POSTGRES_DB: markdown_notes
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:test123456@db:5432/markdown_notes
    # run the FastAPI server
    # install all required dependencies berfore running the command
    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host
    

volumes:
  data: